apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    capabilities: Seamless Upgrades
    categories: Integration & Delivery
    certified: "true"
    description: Foundational components for central management of multiple OpenShift Container Platform and Kubernetes clusters
    repository: https://github.com/open-cluster-management/backplane-operator
    support: Red Hat
  labels:
    control-plane: backplane-operator
  name: multicluster-engine-operator
  namespace: '{{ .Release.Namespace }}'
spec:
  replicas: 2
  selector:
    matchLabels:
      control-plane: backplane-operator
  strategy: {}
  template:
    metadata:
      labels:
        control-plane: backplane-operator
        ocm-antiaffinity-selector: backplane-operator
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: ocm-antiaffinity-selector
                  operator: In
                  values:
                  - backplane-operator
              topologyKey: topology.kubernetes.io/zone
            weight: 70
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: ocm-antiaffinity-selector
                  operator: In
                  values:
                  - backplane-operator
              topologyKey: kubernetes.io/hostname
            weight: 35
      containers:
      - args:
        - --leader-elect
        command:
        - /app/backplane-operator
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OPERAND_IMAGE_ADDON_MANAGER
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/addon-manager-rhel9@sha256:db6b37815ff668e1a16ca7f6aade2dee813677b40808d72398eb0e7a46e8247d'
        - name: OPERAND_IMAGE_AZURE_SERVICE_OPERATOR_RHEL9
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/azure-service-operator-rhel9@sha256:5f920c2bd337f783b5a6ddc4c853ff11618da65182b2bd6fea260caf5456a1ba'
        - name: OPERAND_IMAGE_BACKPLANE_MUST_GATHER
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/must-gather-rhel9@sha256:ce0ed4a40f2c71d5f51c9db9a1b9611a76944d1d032e396f5acd77432adff189'
        - name: OPERAND_IMAGE_BACKPLANE_OPERATOR
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/backplane-rhel9-operator@sha256:3430f986afc84c6c2de72ab7c396cea283891a3072022a4b46ffc7de935f35ee'
        - name: OPERAND_IMAGE_CLUSTER_API_PROVIDER_AGENT
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/cluster-api-provider-agent-rhel9@sha256:2ddf6a7796ff51604ebab1ed5426ebcaa640657fd0ffadfd6931fb0b852adbe4'
        - name: OPERAND_IMAGE_CLUSTER_API_PROVIDER_AWS_RHEL9
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/cluster-api-provider-aws-rhel9@sha256:a82a077ee96d0449715243f3e6d695f414c137000756e5c4b093fef3a820a718'
        - name: OPERAND_IMAGE_CLUSTER_API_PROVIDER_AZURE_RHEL9
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/cluster-api-provider-azure-rhel9@sha256:52da68b9b2200ddd5f28285be17155657238fccac5ff7d04e28c1402431ed36a'
        - name: OPERAND_IMAGE_CLUSTER_API_PROVIDER_KUBEVIRT
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/cluster-api-provider-kubevirt-rhel9@sha256:fd64f8c7c4ab7c2041a87771dbae640a380f9e70cc11be6a98ddcdfc74270a66'
        - name: OPERAND_IMAGE_CLUSTER_API_PROVIDER_OPENSHIFT_ASSISTED_BOOTSTRAP
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/capoa-bootstrap-rhel9@sha256:93c282abd997507d09d397ff5eec6e63928df2dbf87de2d4d67414eabe02c467'
        - name: OPERAND_IMAGE_CLUSTER_API_PROVIDER_OPENSHIFT_ASSISTED_CONTROL_PLANE
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/capoa-control-plane-rhel9@sha256:c5b58b1dde2718dafb5633bd2efbeb7d5df13ea882f653a0927ad4e4c3413a90'
        - name: OPERAND_IMAGE_MCE_CAPI_WEBHOOK_CONFIG_RHEL9
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/mce-capi-webhook-config-rhel9@sha256:17504732fb62bc018221092ecbc17b38fdd66bd5ba974620587b8bb9312e4a73'
        - name: OPERAND_IMAGE_CLUSTERCLAIMS_CONTROLLER
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/clusterclaims-controller-rhel9@sha256:76755ab36c9b9645a0a51214bb3c6c49e99bd5d7b166971bf2e69a92cc25c871'
        - name: OPERAND_IMAGE_CLUSTER_CURATOR_CONTROLLER
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/cluster-curator-controller-rhel9@sha256:027aae909d992ffe8a99c44a52423c455a7e55f25187c75073d645f8b930a7f6'
        - name: OPERAND_IMAGE_CLUSTER_IMAGE_SET_CONTROLLER
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/cluster-image-set-controller-rhel9@sha256:3674816439c95ba1e0b772156ae71de135d7736e8a94ac175fcecb0a154d017d'
        - name: OPERAND_IMAGE_CLUSTERLIFECYCLE_STATE_METRICS
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/clusterlifecycle-state-metrics-rhel9@sha256:0c2afdff2edb9ddf43cfa0551f0421a0a0493f921fd64204011830c399d28f66'
        - name: OPERAND_IMAGE_CLUSTER_PROXY
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/cluster-proxy-rhel9@sha256:cb0f2bb5a4d2e480d301c0acf502bf4c324838a01cc0f8e5c29b8b671fd9dec8'
        - name: OPERAND_IMAGE_CONSOLE_MCE
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/console-mce-rhel9@sha256:f0d3f1f52aff5fb9d78c694899ce12bd4ccc2b5a80f12ff44652467781c772b0'
        - name: OPERAND_IMAGE_DISCOVERY_OPERATOR
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/discovery-rhel9@sha256:1a456f0c673d92307639406753b60405b58d4012eee909798609263c9a8ace00'
        - name: OPERAND_IMAGE_OPENSHIFT_HIVE
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/hive-rhel9@sha256:6e328117ffaaebb8f21d836c0707a785c6001b0df7806dc578005e8785036878'
        - name: OPERAND_IMAGE_HYPERSHIFT_ADDON_OPERATOR
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/hypershift-addon-rhel9-operator@sha256:381e956722910fb361a963a51b7c131fea6eed41cad2682d189e639b33f55143'
        - name: OPERAND_IMAGE_HYPERSHIFT_CLI
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/hypershift-cli-rhel9@sha256:858331b36e7a01272e4c5b6285b2b038356e360003dff188138446f16a5b85c8'
        - name: OPERAND_IMAGE_HYPERSHIFT_OPERATOR
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/hypershift-rhel9-operator@sha256:841f55fc5902a8fb44b62c0a6ad56b37062fe42b618a36129b853b9547781d31'
        - name: OPERAND_IMAGE_IMAGE_BASED_INSTALL_OPERATOR
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/image-based-install-rhel9@sha256:265577c7108a27ff9f67f8d56f86324a02947c1bee932cc9831f3a86506aa228'
        - name: OPERAND_IMAGE_KUBE_RBAC_PROXY_MCE
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/kube-rbac-proxy-mce-rhel9@sha256:6669df74228b206441f5369ae65aa8193ea3b00ce5c93daec301bc07569d1429'
        - name: OPERAND_IMAGE_MANAGEDCLUSTER_IMPORT_CONTROLLER
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/managedcluster-import-controller-rhel9@sha256:8cbae2f9a6fc8dd40b8aec03f2ea278bd670e106ce636bd7fd043facbc6f36bc'
        - name: OPERAND_IMAGE_MANAGED_SERVICEACCOUNT
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/managed-serviceaccount-rhel9@sha256:029e5605e0503fac44e974f722e378f7d79a5f32ed1827fec0778c451a68f95e'
        - name: OPERAND_IMAGE_MULTICLOUD_MANAGER
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/multicloud-manager-rhel9@sha256:a8cef81889422a341a69e957f2cec0d4d8e8567637886d8e0ec4229440ae85c8'
        - name: OPERAND_IMAGE_PROVIDER_CREDENTIAL_CONTROLLER
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/provider-credential-controller-rhel9@sha256:3f855ba78685f23835982fb9481a927538790ace6e48b70ad8a2831dfdc644be'
        - name: OPERAND_IMAGE_PLACEMENT
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/placement-rhel9@sha256:53f4507905077d5211de229c1a82c138285705f3512a6a6bb68c8c37e2ec01aa'
        - name: OPERAND_IMAGE_REGISTRATION
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/registration-rhel9@sha256:12f80e51f06af032e8f216d274a299642fb4a1bc3c9b2d64c99d34807d731925'
        - name: OPERAND_IMAGE_REGISTRATION_OPERATOR
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/registration-operator-rhel9@sha256:66a635eb5d024cfd04895196bd3b7f0bbd19c8d66ef3b997848e0a83f82b105e'
        - name: OPERAND_IMAGE_WORK
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/work-rhel9@sha256:1226e394e5fede97efeb2aae2f793971ef364e4a1aaa46d867d75d436c53209b'
        - name: OPERAND_IMAGE_ASSISTED_IMAGE_SERVICE
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/assisted-image-service-rhel9@sha256:92f37d4e62d0be6705e275da4afcdbb5817bee2cffe10615c27935b0bebebccf'
        - name: OPERAND_IMAGE_ASSISTED_INSTALLER
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/assisted-installer-rhel9@sha256:72e57d484d6ee1880f4ec7e9b324e0ea8dd69e21eaf9b96c9a7e502f3d4af8ad'
        - name: OPERAND_IMAGE_ASSISTED_INSTALLER_AGENT
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/assisted-installer-agent-rhel9@sha256:995f9b9a4727db219c5db7abfbec189c51c169460e9953940ab88bb8d3c47613'
        - name: OPERAND_IMAGE_ASSISTED_INSTALLER_CONTROLLER
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/assisted-installer-controller-rhel9@sha256:fdc0d540b6161016c067f694ca727c9f5cf857f7df2f199e1490879c39cb8036'
        - name: OPERAND_IMAGE_ASSISTED_SERVICE_9
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/assisted-service-9-rhel9@sha256:ff4f6ed0dc07e2be6093e4532232d73d3e27e92b615608abf93e5dbd6d329c2e'
        - name: OPERAND_IMAGE_OSE_CLUSTER_API_RHEL9
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/ose-cluster-api-rhel9@sha256:10de81107196991519e6507df291ad3c2352a1792b1b1b36d466eea73f022bae'
        - name: OPERAND_IMAGE_OSE_BAREMETAL_CLUSTER_API_CONTROLLERS_RHEL9
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/ose-baremetal-cluster-api-controllers-rhel9@sha256:9c1293eaf36a9893fc8e3952aff8d43fb450a86cace31979b16d7b77edcaffe4'
        - name: OPERAND_IMAGE_POSTGRESQL_13
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/postgresql-13@sha256:19266ff13a81c85d42e53734e375a5d341221b2c161ca41d009cc6fbe8906ea2'
        - name: OPERATOR_VERSION
          value: 2.11.1
        - name: OPERATOR_PACKAGE
          value: multicluster-engine
        image: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/backplane-rhel9-operator@sha256:3430f986afc84c6c2de72ab7c396cea283891a3072022a4b46ffc7de935f35ee'
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: backplane-operator
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 20Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      nodeSelector:
        aro-hcp.azure.com/role: infra
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: multicluster-engine-operator
      terminationGracePeriodSeconds: 10
      tolerations:
      - effect: NoSchedule
        key: infra
        operator: Equal
        value: "true"
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: multicluster-engine-operator-webhook
status: {}
