apiVersion: v2
appVersion: 2.11.1
description: A Helm chart for multicluster-engine - CRDs
keywords:
- mce
- multicluster-engine
- multiclusterengine
name: multicluster-engine-crds
sources:
- quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mce-operator-bundle-mce-211@sha256:bea8c65546b3961f2e3bc07142c4a992ce28b9b62ccb6c2d2bf2cf607839ae1d
type: application
version: 2.11.1
