apiVersion: v2
appVersion: 2.11.1
description: A Helm chart for multicluster-engine - CRDs
keywords:
- mce
- multicluster-engine
- multiclusterengine
name: multicluster-engine-crds
sources:
- quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mce-operator-bundle-mce-211@sha256:0081161dd8f61845417594ede3af90447fba743e07dac67fbbb528f152096966
type: application
version: 2.11.1
