apiVersion: v2
appVersion: 2.11.1
description: A Helm chart for multicluster-engine - CRDs
keywords:
- mce
- multicluster-engine
- multiclusterengine
name: multicluster-engine-crds
sources:
- quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mce-operator-bundle-mce-211@sha256:cf25180fa64d015adc4ca212ed24f47a454fa89877fb7d8877274a2ba485aa40
type: application
version: 2.11.1
