apiVersion: v2
appVersion: 2.11.1
description: A Helm chart for multicluster-engine
keywords:
- mce
- multicluster-engine
- multiclusterengine
name: multicluster-engine
sources:
- quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mce-operator-bundle-mce-211@sha256:6ff83a6761ea3eeeb7b97a7e13e09bba5e5beb60bc6d1fe44709c7a8f22bf2e5
type: application
version: 2.11.1
