apiVersion: v2
appVersion: 2.11.1
description: A Helm chart for multicluster-engine
keywords:
- mce
- multicluster-engine
- multiclusterengine
name: multicluster-engine
sources:
- quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mce-operator-bundle-mce-211@sha256:e28783efffea050d686b756270ea5ec9ae92402e7b5fa032e8605075dd1d89ad
type: application
version: 2.11.1
